### PR TITLE
Migrate SGTS content to Products

### PR DESCRIPTION
**Pull request by candyyap-gvt**
Move SHIP-HATS back to DevOps

### CODE REVIEW

**Review by yanbutan — APPROVED** [review]
Looks good to me (LGTM) @teochengyong @phaelar what do you guys think?

**Comment by phaelar** [comment]
\

> Looks good to me (LGTM) @teochengyong @phaelar what do you guys think?

you've been referencing the wrong Raphael :laughing:

**Comment by yanbutan** [comment]
> > Looks good to me (LGTM) @teochengyong @phaelar what do you guys think?
> 
> you've been referencing the wrong Raphael 😆

hahaha. This is embarrassing, supposed to be @kuramochi-coder cc: @candyyap-gvt .

**Review by teochengyong — APPROVED** [review]
LGTM finally getting these content to a proper home @candyyap-gvt 😄

**Review by kuramochi-coder — APPROVED** [review]

**Pull request merged**
