### PR TITLE
697 carousel hero banner

### PR DESCRIPTION
**Pull request by anbarisker**
Change logs:
1. Carousel.js, Carousel.scss
2. Include slider type of carousel for home page.

### CODE REVIEW

**Comment by Ducksss** [comment]
Hey @anbarisker, I noticed that the carousel with the blue page image and content is obscured or positioned too high for the readers. I loaded a past instance (February 10th, 2022) and it reaffirmed the point that the content is positioned way too high.

Screenshot 2022-07-29 at 4 31 46 PM
^ Before the update

Screenshot 2022-07-29 at 4 33 16 PM
^ After the update

**Comment by Ducksss** [comment]
Also, when the buttons are clicked rapidly, the bottom navigational bar seems to reflect the changes, but the content does not. Perhaps we can explore into a solution where both the bottom navigational bar and the carousel buttons are disabled when a button is pressed and is reenabled .500 seconds later. Perhaps you can check this out: https://www.mercedes-benz.com/en/

https://user-images.githubusercontent.com/58126222/181719962-444cd62d-0b40-4c12-9608-1859fb6a7c39.mov

**Comment by Ducksss** [comment]
Also, I personally feel that 5 seconds is a little too fast before the carousel transitions. Perhaps we can raise it up to 7.5s

**Comment by Ducksss** [comment]
Lastly, after going to a different page, the interval or seconds before it resets do not change. As such, since we will transition to a different page at t5s, if a user have navigated to another page at t4s, it will transition back to a next page.

https://user-images.githubusercontent.com/58126222/181724903-07569b22-b313-4f65-86fc-7f1d8d089db7.mov

**Comment by Ducksss** [comment]
The mobile view is a little glitchy when pressing the buttons to navigate the carousel.

https://user-images.githubusercontent.com/58126222/185542657-e59e7d77-a76e-4ee7-b4f6-24c74bc051ea.MOV

**Comment by Ducksss** [comment]
There is also a flash when swiping to different pages.

https://user-images.githubusercontent.com/58126222/185542955-af9037ac-1b59-4836-a4e4-1ff7711ee99c.MOV

**Comment by teochengyong** [comment]
@anbarisker this PR is no longer needed right?

**Comment by anbarisker** [comment]
> 

yep, let me close it

**Pull request closed without merging**
