### PR TITLE
PinZheng Static Code Scanning Tool Integration

### PR DESCRIPTION
**Pull request by Ducksss**
# Summary
Configuring CodeQL into our GitHub workflow for static code scanning purposes, helping to improve the Developer Portal's security and reliability.

## Description of CodeQL Configs
- Language to scan: JavaScript and Ruby
- Cron Job: 2 AM Singapore Time, every day -> scan master branch
- Scans master on every push
- Scans individual subsets of master branch, e.g. Prs
- Alerts with high severity have to be addressed before merging 

### List of errors from my forked repository of developer.gov.sg
Screenshot 2022-11-30 at 3 51 18 PM

### Detail description of an error from my forked repository of developer.gov.sg
Screenshot 2022-11-30 at 3 51 42 PM

### Scanning on individual prs
image

### CODE REVIEW

**Comment by Ducksss** [comment]
# Insufficient Regex
Previously, a test email: abc@aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa!.techpass.gov.sg will cause the JavaScript engine “hangs” with 100% CPU consumption. 

Why? The reason is that a word, `abc@aaaaaaaaa!.techpass.gov` -> `aaaaaaaaa!`, can be represented as one \w+ or many:
(aaaaaaaaa)
(aaaaaaaa)(a)
(aaaaaaa)(aa)
(aaaaaa)(aaa)
...

As a result, there are 2n-1, where n is the length of the sequence. For aaaaaaaaa! we have n=9, that gives 511 combinations. For a longer sequence with n=20 there are about one million (1048575) combinations. For n=30 – a thousand times more (1073741823 combinations).

Resources on regex-catastrophic-backtracking:
https://javascript.info/regexp-catastrophic-backtracking

Old Code Sample:
```html
<!DOCTYPE html>
<script>
"use strict";

let regexp = /^[a-zA-Z0-9.#$%&'*+/=?^_`{|}~-]+@(\w+.)*gov\.sg$/;
let str = "abc@aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa!.techpass.gov.sg";

// will take a very long time
alert( regexp.test(str) );
</script>
```

**Comment by Ducksss** [comment]
# Adding JQuery Integrity and Cross origin information
Including a resource from an untrusted source or using an untrusted channel may allow an attacker to include arbitrary code in the response. When including an external resource (for example, a script element or an iframe element) on a page, it is important to ensure that the received data is not malicious.

**Comment by Ducksss** [comment]
# Potentially unsafe external link that might redirect and access the DOM 
HTML links that open in a new tab or window allow the target page to access the DOM of the origin page using window.opener unless link type noopener or noreferrer is specified. This is a potential security risk.

**Review by teochengyong — APPROVED** [review]
Looks good to me! Good job making the site safer 😄

**Comment by Ducksss** [comment]
Thanks Cheng Yong 😄

**Pull request merged**
