### PR TITLE
Choihonghui pab update

### PR DESCRIPTION
**Pull request by choihonghui**

### CODE REVIEW

**Review by HazelKoh12 — COMMENTED** [review]
the overview section does not provide the background/backstory on why pab was created, or the social issue that it addresses, can the team add in more info?

**Comment by choihonghui** [comment]
> the overview section does not provide the background/backstory on why pab was created, or the social issue that it addresses, can the team add in more info?

Added in numbers Joyce provided for when the product team made their awards submission

**Comment by choihonghui** [comment]
> Added in numbers Joyce provided for when the product team made their awards submission

Updates:
1) Joyce and Joy verified that the numbers are correct.
2) Joy doesn't have anything more to add regarding why PAB was created.
3) Candy shared with me a [writeup](https://www.tech.gov.sg/media/technews/designing-a-wearable-that-could-save-lives) regarding **portable** PAB. I checked with Joy whether to include this, and her response is no, because portable PAB didn't get pass prototype stage.

**Review by HazelKoh12 — COMMENTED** [review]
i have emailed you some content for pab, for pab there were a few media features that were published, you can search online for more content. Understand that portable PAB did not pass the prototype stage, you can dismiss that link in my email

**Comment by choihonghui** [comment]
> i have emailed you some content for pab, for pab there were a few media features that were published, you can search online for more content. Understand that portable PAB did not pass the prototype stage, you can dismiss that link in my email

Thanks for the links. I looked through them but they don't seem to provide more info about why PAB was created.

[Si-yan's blog](https://siyan.co/projects/pab) does have some new info, but it's about technical specifications. Ok to add these in? (Pasting below)

- Built with Java Spring Boot (for backend services) and React (for web applications)
- Uses microservices architecture, with multiple self-contained services communicating with each other through HTTP calls and ActiveMQ messaging
- Deployed using Docker Swarm
- Databases used: MySQL, Cassandra

**Review by HazelKoh12 — COMMENTED** [review]
work with si yan and joy to see where the information can be added in where it is updated/outdated etc, conduct more online research to see where the overview section can be enhanced.

**Review by HazelKoh12 — APPROVED** [review]

**Pull request merged**
