### PR TITLE
CFT GA Date updates + minor writing updates

### PR DESCRIPTION
**Pull request by leysanchez**
- Updated GA date
- Updated minor writing content

Important: Will update the table of features image soon once the updated table is provided by product manager. Will comment out the outdated table for now.

### CODE REVIEW

**Review by candyyap-gvt — CHANGES_REQUESTED** [review]
@leysanchez for the changes in the features page, are you including the new uploaded picture? Currently it has been commented off.

**Comment by leysanchez** [comment]
> @leysanchez for the changes in the features page, are you including the new uploaded picture? Currently it has been commented off.

Hi @candyyap-gvt, I've commented off for now because I am waiting for newer version of the image from prod manager. Team asked me to commit the GA dates first and the image can be updated again probably later this week. I commented off because it original image contains outdated info.

Is that ok?

**Comment by candyyap-gvt** [comment]
> > @leysanchez for the changes in the features page, are you including the new uploaded picture? Currently it has been commented off.
> 
> Hi @candyyap-gvt, I've commented off for now because I am waiting for newer version of the image from prod manager. Team asked me to commit the GA dates first and the image can be updated again probably later this week. I commented off because it original image contains outdated info.
> 
> Is that ok?

**Comment by candyyap-gvt** [comment]
> > @leysanchez for the changes in the features page, are you including the new uploaded picture? Currently it has been commented off.
> 
> Hi @candyyap-gvt, I've commented off for now because I am waiting for newer version of the image from prod manager. Team asked me to commit the GA dates first and the image can be updated again probably later this week. I commented off because it original image contains outdated info.
> 
> Is that ok?

@leysanchez yeap is fine. Will proceed to merge it. Appreciate it if you can remove the outdated image once the image is finalised. Thanks

**Comment by leysanchez** [comment]
> > > @leysanchez for the changes in the features page, are you including the new uploaded picture? Currently it has been commented off.
> > 
> > 
> > Hi @candyyap-gvt, I've commented off for now because I am waiting for newer version of the image from prod manager. Team asked me to commit the GA dates first and the image can be updated again probably later this week. I commented off because it original image contains outdated info.
> > Is that ok?
> 
> @leysanchez yeap is fine. Will proceed to merge it. Appreciate it if you can remove the outdated image once the image is finalised. Thanks

Thanks Candy. Will do! I'll keep just one image for this.

**Review by candyyap-gvt — APPROVED** [review]

**Pull request merged**
