### PR TITLE
Resolving the issue of empty cards surfacing in the search results

### PR DESCRIPTION
**Pull request by Ducksss**
After realizing that the reason why empty cards surface is that they are lacking parameters such as { title: "", content: "" }, a filter was created. The filter removes empty strings, white spaces and empty HTML tags. Examples includes strings such as "", " ", "`<p></p>`" tags etc.

Beforeand after snapshot:
image

### CODE REVIEW

**Comment by teochengyong** [comment]
@Ducksss @yanbutan will help to review the PR 😄

**Comment by yanbutan** [comment]
This solves the problem by removing all of the empty results. Actually @Ducksss does it work on your local? I think the regex removes all search results on my local, and in the aws amplify link above also.

Anyways, it removes empty results, but those results were actually sub pages within a product page. For e.g

Screenshot 2022-04-06 at 2 53 29 PM

The first empty search result is actually a sub page under personalise.

Screenshot 2022-04-06 at 2 54 13 PM

I dont think we will want to exclude these pages from our page (@teochengyong right? just to double confirm, hahah), so we probably shouldn't just filter them out. I dug down last time and the culprit is actually in the /search/pages.json, specifically the top portion.

Screenshot 2022-04-06 at 2 58 36 PM

We're using [jekyll](https://jekyllrb.com/) with [liquid](https://shopify.github.io/liquid/) to build this json which extracts all pages (first part) and collections (second part with the site.documents). We then do our lunr indexing and searching on this json.

Our web app's posts are mainly in 3 places pages, collections and in the root. 

Screenshot 2022-04-06 at 3 02 50 PM
Screenshot 2022-04-06 at 3 03 21 PM
Screenshot 2022-04-06 at 3 03 38 PM

The first portion of this file is returning empty data for files like getting-started.html, contact-us.html,etc and I dont know the reason why. The second portion which only looks through site.documents or collections does fetch the correct data.

Screenshot 2022-04-06 at 3 07 31 PM
Screenshot 2022-04-06 at 3 08 23 PM

(**sidenote**, you might notice the duplicated title, we'll discuss that later) As can be seen, data is being returned. But my guess is when combined with the first portion, it overrides the results retrieved in the second.

Solution for this will be to have the first portion target search only within pages folder or root folder while ignoring the collections folder. Or some other easier ways might exist, you can explore different solutions bah @Ducksss. It might be helpful for you to understand how jekyll works first especially the [collections](https://jekyllrb.com/docs/step-by-step/09-collections/) part.

Addressing the **sidenote** above, it would seem that the results are duplicated, but it's actually different pages that has the same parent page as shown in the screenshots above. How to solve this? I'm thinking for sub-pages, we could have a front-matter `sub_page_title: ...` or simply just add the sub page e.g `Getting Started` to the end of the title :

Screenshot 2022-04-06 at 3 18 03 PM

@Ducksss you can also explore how to do this elegantly also hahahah 👍 . If there's any doubts, can always hop on a call.
@teochengyong in case you wanna look through.

**Comment by Ducksss** [comment]
Thanks for taking the time to write these comments @yanbutan, I will look into Jekyll and Liquid 👍🏻 I originally thought a simple filter to remove when the title is empty would do, as I thought the output response was from a database (maybe corrupted data entry?) and was absolute instead of extraction from all the pages. Maybe I could research more on the first portion of the /search/page.json file to better understand why the file has returned empty data for files like getting-started.html, contact-us.html, etc together with understanding what a collection is.

Btw, updated the Regex in the latest pull, do lmk if there are any issues 🙂 tyty
image
image

**Review by yanbutan — APPROVED** [review]
@Ducksss  LGTM! Just need to add a change log in the PR description and update the [playbook](https://confluence.ship.gov.sg/display/DEV/Updated+Products+Collection+Playbook).

**Pull request merged**
