### PR TITLE
Improved search composition

### PR DESCRIPTION
**Pull request by Ducksss**
# Improved search experience 
This Pull Request should address some of the bugs and edge cases raised by @yanbutan. An example of an edge case would be the all products input query leaking into the full site search bar inputs. 

It also addresses other issues, such as determining which form values are used for the query. It's because the previous method would query all the forms and parse each form to see if it had a value. As a result, the previous method only works on a first-come, first-served basis and may be inaccurate when switching between device viewport and width.

Other notable changes would be updating from OptionsAPI to CompositionAPI (thanks @yanbutan ❤️ ) and handling state management with session storage as compared to parsing params from the URL. Added additional functionalities such as expiring the session storage after 30 minutes to reset the user experience. Changed local storage to session storage to clear the values after a session (until the browser is closed)

P.S. (Refactored the code so that it's modularised and are reusable components as mentioned by @teochengyong )

## Alternative methods for state persistence 
Screenshot 2022-06-06 at 2 29 49 PM

## Changing the method of queries
https://user-images.githubusercontent.com/58126222/172106465-de1550ab-f902-4834-a862-791221cc6a20.mov

## Handling Edge cases
https://user-images.githubusercontent.com/58126222/172106531-e319e194-1c71-42e3-a7e7-79491de059ce.mov

## Refactoring the code
Screenshot 2022-06-06 at 2 33 18 PM

### CODE REVIEW

**Comment by Ducksss** [comment]
My god. Forgot a `/` in between `/search/?query=${query}`. Finally works.

**Comment by teochengyong** [comment]
@Ducksss there is a build failure https://ap-southeast-1.console.aws.amazon.com/amplify/home?region=ap-southeast-1#/d2ox9xl4t2suu6/pr-1277/5

**Comment by teochengyong** [comment]
@Ducksss for the search result, it is quite odd the checking the community tab will still show the search result for guidelines

image

**Review by teochengyong — APPROVED** [review]
Looks good to me now!

**Pull request merged**
